import {
  IonAccordion,
  IonAccordionGroup,
  IonBadge,
  IonButton,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonCheckbox,
  IonChip,
  IonContent,
  IonDatetime,
  IonFab,
  IonFabButton,
  IonFooter,
  IonGrid,
  IonHeader,
  IonIcon,
  IonImg,
  IonInput,
  IonItem,
  IonLabel,
  IonList, IonListHeader,
  IonMenu,
  IonMenuButton,
  IonNav,
  IonProgressBar,
  IonRadio,
  IonRadioGroup,
  IonRange,
  IonSearchbar,
  IonSelect,
  IonSelectOption,
  IonSpinner,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonTextarea,
  IonToggle,
  IonToolbar,
  IonToast,
  IonText,
  IonCol,
  IonRow,
  IonSegment, IonSegmentButton, IonCardSubtitle, IonTitle, IonPopover,
  IonButtons, IonRouterOutlet, IonMenuToggle,
  IonSplitPane, IonAlert
} from '@ionic/angular/standalone';

// Exporta todos los módulos en un arreglo
export const IONIC_STANDALONE_MODULES = [
  IonAccordion,
  IonAccordionGroup,
  IonBadge,
  IonButton,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonCheckbox,
  IonChip,
  IonContent,
  IonDatetime,
  IonFab,
  IonFabButton,
  IonFooter,
  IonGrid,
  IonHeader,
  IonIcon,
  IonImg,
  IonInput,
  IonItem,
  IonLabel,
  IonList,
  IonMenu,
  IonMenuButton,
  IonNav,
  IonProgressBar,
  IonRadio,
  IonRadioGroup,
  IonRange,
  IonSearchbar,
  IonSelect,
  IonSelectOption,
  IonSpinner,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonTextarea,
  IonToggle,
  IonToolbar,
  IonToast,
  IonText,
  IonCol,
  IonRow,
  IonSegment, IonSegmentButton,
  IonFab, IonFabButton,
  IonSpinner,
  IonCardTitle,
  IonCardSubtitle,
  IonTitle,
  IonPopover,
  IonButtons,
  IonRouterOutlet,
  IonMenuToggle,
  IonSplitPane,
  IonRouterOutlet,
  IonAlert,
  IonListHeader
];
