name: Build iOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # Instalar Node y npm
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: |
          cd bnm-app
          npm install

      # Instalar CocoaPods
      - name: Install CocoaPods
        run: |
          cd bnm-app/ios/App
          pod install

      # Aquí vendrían los pasos para compilar con Xcode o tu flujo
