name: CI para iOS + Web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias npm
      run: npm install

    - name: Volver al root
      run: echo "Ahora construimos la app iOS"
      working-directory: .

    - name: Instalar CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install

    - name: Construir iOS
      run: |
        cd ios
        xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphoneos -derivedDataPath build
